header:
  version: 17
defaults:
  repos:
    branch: scarthgap
repos:
  meta-oe:
    url: "https://git.openembedded.org/meta-openembedded"
    path: layers/meta-openembedded
    layers:
      meta-oe:
local_conf_header:
  meta-fpga-embedded-dev: |
    EXTRA_IMAGE_FEATURES:append = " ssh-server-openssh"
    IMAGE_INSTALL:append = " packagegroup-fpga-embedded-tools"
