header:
  version: 17
  includes:
    - repo: meta-altera-fpga
      file: kas/bsp.yml
local_conf_header:
  meta-altera-fpga-base: |
    PATCHRESOLVE = "noop"
    USER_CLASSES = "buildstats"
    VIRTUAL-RUNTIME_dev_manager = "udev"
    VIRTUAL-RUNTIME_init_manager = "systemd"
    DISTRO_FEATURES:append = " systemd usrmerge"
    EXTRA_IMAGE_FEATURES = "debug-tweaks"
    IMAGE_INSTALL:append = " kernel-modules"
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
