header:
  version: 17
repos:
  meta-oe:
    url: "https://git.openembedded.org/meta-openembedded"
    commit: 205638f9edf8e1aa1fbcf28555625fe56f2701a5
    branch: scarthgap
    path: layers/meta-openembedded
    layers:
      meta-oe:
local_conf_header:
  meta-altera-fpga-dev: |
    EXTRA_IMAGE_FEATURES:append = " ssh-server-openssh"
    IMAGE_INSTALL:append = " \
        packagegroup-fpga-embedded-tools \
        git \
    "
